version: '3.6'

services:
  cloudshell:
    image: hub.foundries.io/arduino/cloudshell:latest
    restart: always
    tty: true
    read_only: true
    user: "63"
    tmpfs:
    - /run
    - /var/lock
    - /var/log
    - /tmp
    ports:
    - "8000:8000"
